### ISSUE TITLE
Fix unbounded timeout for test HTTP requests

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/serverless-sample-tester#16]
### Current Behavior

"Endpoint Validation" HTTP requests have no timeout. As such, certain types of test failures could lead to tests being stuck for minutes or hours.

### Proposed Solution

Instead of using `http.DefaultClient` in [`makeTestRequest()`](https://github.com/GoogleCloudPlatform/serverless-sample-tester/blob/0336f96af020afb62f6de616b19196d0cde711c5/internal/util/endpoints.go#L108), create a new HTTP client, stored as a global variable, and explicit set a default timeout, perhaps ~10 seconds.

---

This issue affects two categories in my review of the repository:
* **Experience**: Does the project provide a good experience to users?
* **Internals**: Is the implementation efficient, effective, and maintainable?

**Comment by SaketramDurbha** [comment]
Draft implementation here: https://github.com/SaketramDurbha/serverless-sample-tester/tree/i16
Stacked on top of: https://github.com/SaketramDurbha/serverless-sample-tester/tree/i18
