### ISSUE TITLE
Error message formatting

### ISSUE THREAD

**Issue by SaketramDurbha** [GoogleCloudPlatform/serverless-sample-tester#4]
Error messages are currently formatted like this:
```
if err != nil {
    fmt.Errorf("[{package/struct name}.{function name}] {what we were trying to do}: %v", err)
}
```

Per @tritone, we can drop the `[ ]` around the package/struct name and function name:
```
if err != nil {
    fmt.Errorf("{package/struct name}.{function name} {what we were trying to do}: %v", err)
}
```

**Comment by grayside** [comment]
Agreed. Furthermore, the `{package name/struct type name}` should be for the called function, not the current function.

This issue affects one category in my review of the repository:
* **Internals**: Is the implementation efficient, effective, and maintainable?

**Comment by SaketramDurbha** [comment]
Draft implementation: https://github.com/SaketramDurbha/serverless-sample-tester/tree/i4
